apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      name: identity
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: playeconomy.azurecr.io/play.identity:1.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceBusSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: servicebus-connectionstring
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: cosmosdb-connectionstring
            - name: IdentitySettings__AdminUserPassword
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: admin-password
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    app: identity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080